### PR TITLE
Tests for _seismic_dataset.py

### PR DESCRIPTION
**Pull request by Gijsbertbas**
Add test for _seismic_dataset.py, includes usage of hypothesis as test data provider

Included are a few enhancements for _cli.py and its tests.

### CODE REVIEW

**Comment by trhallam** [comment]
I think we need to talk about where `__version__` comes from. At the moment I have it autogenerated by setuptools-scm in a file called version.py in root/segysak/.

**Comment by Gijsbertbas** [comment]
> I think we need to talk about where `__version__` comes from. At the moment I have it autogenerated by setuptools-scm in a file called version.py in root/segysak/.

Yes read your discussion about autoversioning but didn't really see how to use it... how would I extract the version from there? Or should we abolish stating the version with the cli?

**Comment by trhallam** [comment]
You should be able to just use 
```
from version import version
```
Perhaps for testing we can put a try except and set it to `0.0.0` in case people are trying to do things without running setup.py

**Comment by Gijsbertbas** [comment]
I took the `Programmatic usage` example from [setuptools-scm](https://pypi.org/project/setuptools-scm/).

I removed using the version in the test, we don't need to test the version in the _cli test (perhaps we should write a separate version test?)

**Pull request merged**
